from enum import Enum


class ProductsCategory(str, Enum):
    ELETRONICO = "ELETRONICO"
    MOVEIS = "MOVEIS"
    UTENSILIOS = "UTENSILIOS"
    VESTUARIO = "VESTUARIO"
    ALIMENTICIO = "ALIMENTICIO"
    LIVROS = "LIVROS"
    BRINQUEDOS = "BRINQUEDOS"
    BELEZA = "BELEZA"
    ESPORTE = "ESPORTE"
    AUTOMOTIVO = "AUTOMOTIVO"
    SAUDE = "SAUDE"
    JARDINAGEM = "JARDINAGEM"
    FERRAMENTAS = "FERRAMENTAS"
    INFORMATICA = "INFORMATICA"
    TELEFONIA = "TELEFONIA"
    MUSICA = "MUSICA"
    ARTES = "ARTES"
    PETSHOP = "PETSHOP"
    VIAGEM = "VIAGEM"
    OUTROS = "OUTROS"
